# Generated by Django 5.0.6 on 2025-02-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('date', models.DateField()),
                ('vender', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
